### ISSUE TITLE
ESPlorer Problems

### ISSUE THREAD

**Issue by brightmoon03** [squix78/esp8266-projects#1]
When I go to the ESPlorer link, and click the download button, it 1; Takes a long time to download the file. 2; When I open the folder, an error pops up, saying that the file is invalid. 

Can anyone help? 

Thanks, Samuel M

**Comment by squix78** [comment]
Hi Samuel

I just downloaded ESPlorer and it looks fine. Have you used this link, which is a bit hidden between the advertisment? http://esp8266.ru/esplorer-latest/?f=ESPlorer.zip
Then you'll have to unpack the zip file. The content is a JAR file, which is JAR executable. On a windows system you might run ESPlorer.bat
On a MAC or oder Unix-like system open the command line and type java -jar ESPlorer.jar from the folder you unzipped.
If that doesn't work, it would be helpful to get more information:
- your operating system
- what happens when you run "java -version" from the command line
- screenshot of the error message

**Comment by brightmoon03** [comment]
I got this worked out! Thanks!
